local ATTACKER_TYPES = {}
ATTACKER_TYPES[0] = 'weapon'
ATTACKER_TYPES[1] = 'barrelbombl'
ATTACKER_TYPES[2] = 'makimushi'
ATTACKER_TYPES[3] = 'nitro'
ATTACKER_TYPES[4] = 'onibimine'
ATTACKER_TYPES[5] = 'ballistahate'
ATTACKER_TYPES[6] = 'capturesmokebomb'
ATTACKER_TYPES[7] = 'capturebullet'
ATTACKER_TYPES[8] = 'barrelbombs'
ATTACKER_TYPES[9] = 'kunai'
ATTACKER_TYPES[10] = 'waterbeetle'
ATTACKER_TYPES[11] = 'detonationgrenade'
ATTACKER_TYPES[12] = 'hmballista'
ATTACKER_TYPES[13] = 'hmcannon'
ATTACKER_TYPES[14] = 'hmgatling'
ATTACKER_TYPES[15] = 'hmtrap'
ATTACKER_TYPES[16] = 'hmnpc'
ATTACKER_TYPES[17] = 'hmflamethrower'
ATTACKER_TYPES[18] = 'hmdragonator'
ATTACKER_TYPES[19] = 'otomo'
ATTACKER_TYPES[20] = 'fg005'
ATTACKER_TYPES[21] = 'ecbatexplode'
ATTACKER_TYPES[23] = 'monster'

local ATTACKER_TYPE_TEXT = {}
ATTACKER_TYPE_TEXT['weapon']            = 'Weapon'
ATTACKER_TYPE_TEXT['barrelbombl']       = 'Large Barrel Bomb'
ATTACKER_TYPE_TEXT['makimushi']         = 'makimushi'
ATTACKER_TYPE_TEXT['nitro']             = 'nitro'
ATTACKER_TYPE_TEXT['onibimine']         = 'onibimine'
ATTACKER_TYPE_TEXT['ballistahate']      = 'ballistahate'
ATTACKER_TYPE_TEXT['capturesmokebomb']  = 'Tranq Bomb'
ATTACKER_TYPE_TEXT['capturebullet']     = 'Tranq Ammo'
ATTACKER_TYPE_TEXT['barrelbombs']       = 'Barrel Bomb'
ATTACKER_TYPE_TEXT['kunai']             = 'Kunai'
ATTACKER_TYPE_TEXT['waterbeetle']       = 'waterbeetle'
ATTACKER_TYPE_TEXT['detonationgrenade'] = 'detonationgrenade'
ATTACKER_TYPE_TEXT['hmballista']        = 'Ballista'
ATTACKER_TYPE_TEXT['hmcannon']          = 'Cannon'
ATTACKER_TYPE_TEXT['hmgatling']         = 'Machine Cannon'
ATTACKER_TYPE_TEXT['hmtrap']            = 'Bamboo Bomb'
ATTACKER_TYPE_TEXT['hmnpc']             = 'Defenders'
ATTACKER_TYPE_TEXT['hmflamethrower']    = 'Wyvernfire'
ATTACKER_TYPE_TEXT['hmdragonator']      = 'Dragonator'
ATTACKER_TYPE_TEXT['otomo']             = 'Buddy'
ATTACKER_TYPE_TEXT['fg005']             = 'fg005'
ATTACKER_TYPE_TEXT['ecbatexplode']      = 'ecbatexplode'
ATTACKER_TYPE_TEXT['monster']           = 'Monster'

local function export()
	return ATTACKER_TYPES, ATTACKER_TYPE_TEXT;
end

return export;